<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "realer"
 *
 * Auto generated by Extension Builder 2017-08-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Real estate publisher',
    'description' => 'Provides information regarding real estate properties',
    'category' => 'plugin',
    'author' => 'Roman Büchler',
    'author_email' => 'rb@buechler.pro',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
